/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clase.ColaConCorrimiento;
import Clase.ColaSimple;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HiYeaismin 8a
 */
public class Colas extends javax.swing.JFrame {

    ColaSimple colaSimple = new ColaSimple();
    ColaConCorrimiento colaConCorrimiento = new ColaConCorrimiento();

    /**
     * Creates new form Colas
     */
    public Colas() {
        initComponents();
        mostrarColaSimple();
        this.setLocationRelativeTo(null);
        lblInsertar.setText("Tamaño:");
        radioBtn.setVisible(false);
        radioBtn2.setVisible(false);
        btnEliminar.setVisible(false);
        //--
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntGrupo = new javax.swing.ButtonGroup();
        lblInsertar = new javax.swing.JLabel();
        txtInsertar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        radioBtn = new javax.swing.JRadioButton();
        radioBtn2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInsertar.setText("Valor:");

        txtInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertarActionPerformed(evt);
            }
        });
        txtInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInsertarKeyPressed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        bntGrupo.add(radioBtn);
        radioBtn.setText("Simple");

        bntGrupo.add(radioBtn2);
        radioBtn2.setText("Corrim.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn2))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtn)
                    .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertar))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertarActionPerformed
    public void mostrarColaSimple() {
        if (colaSimple.valorIni() == -1) {
            jTextArea1.setText("Cola vacia");
            return;
        }
        String cadena = "";
        int copiaIni = colaSimple.valorIni();
        int copiaFin = colaSimple.valorFin();
        char copiaCola[] = colaSimple.contenidoCola();

        for (int i = copiaIni; i <= copiaFin; i++) {
            cadena += "[" + i + "]" + copiaCola[i] + " ";
        }
        cadena = "Ini: " + copiaIni + "\nFin: " + copiaFin + "\n" + cadena;
        jTextArea1.setText(cadena);

    }

    public void mostrarColaCorrimiento() {
        if (colaConCorrimiento.valorIni() == -1) {
            jTextArea1.setText("Cola vacia");
            return;
        }
        String cadena = "";
        int copiaIni = colaConCorrimiento.valorIni();
        int copiaFin = colaConCorrimiento.valorFin();
        char copiaCola[] = colaConCorrimiento.contenidoCola();

        for (int i = copiaIni; i <= copiaFin; i++) {
            cadena += "[" + i + "]" + copiaCola[i] + " ";
        }
        cadena = "Ini: " + copiaIni + "\nFin: " + copiaFin + "\n" + cadena;
        jTextArea1.setText(cadena);

    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:}
        if (radioBtn.isSelected()==true) {
            boolean resultado = colaSimple.eliminar();
            if (resultado == true) {
                JOptionPane.showMessageDialog(this, "valor eliminado: " + colaSimple.valorEliminador());
                mostrarColaSimple();
            } else {
                JOptionPane.showMessageDialog(this, "Cola vacía.");

            }
        }
        if (radioBtn2.isSelected()==true) {
            boolean resultado = colaConCorrimiento.eliminar();
            if (resultado == true) {
                JOptionPane.showMessageDialog(this, "valor eliminado: " + colaConCorrimiento.valorEliminador());
                mostrarColaCorrimiento();
            } else {
                JOptionPane.showMessageDialog(this, "Cola vacía.");

            }

        }


    }//GEN-LAST:event_btnEliminarActionPerformed
    public void insertarkey(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try{
            if (lblInsertar.getText() == "Tamaño:") {
                colaSimple.setTamaño(Integer.parseInt(txtInsertar.getText()));
                colaConCorrimiento.setTamaño(Integer.parseInt(txtInsertar.getText()));
                colaConCorrimiento.inicializararreglo();
                colaSimple.inicializararreglo();
                txtInsertar.setText("");
                lblInsertar.setText("Valor:");
                btnEliminar.setVisible(true);
                radioBtn.setVisible(true);
                radioBtn2.setVisible(true);
            }

            if (radioBtn.isSelected() == true) {
                boolean resultado = colaSimple.insertar(txtInsertar.getText().charAt(0));
                if (resultado == true) {
                    JOptionPane.showMessageDialog(this, "Se insertó valor.");
                    txtInsertar.setText("");
                    mostrarColaSimple();
                } else {
                    JOptionPane.showMessageDialog(this, "Cola llena");
                    txtInsertar.setText("");
                }
            }

            if (radioBtn2.isSelected()) {
                boolean resultado = colaConCorrimiento.insertar(txtInsertar.getText().charAt(0));
                if (resultado == true) {
                    JOptionPane.showMessageDialog(this, "Se insertó valor.");
                    txtInsertar.setText("");
                    mostrarColaCorrimiento();

                } else {
                    JOptionPane.showMessageDialog(this, "Cola llena");
                    txtInsertar.setText("");
                }
            }
            }catch(StringIndexOutOfBoundsException error){
                JOptionPane.showMessageDialog(this, "No insertar espacios.");
            }catch(NumberFormatException error){
                JOptionPane.showMessageDialog(this, "No ingresar simbolos.");
            }

        }
    }
    private void txtInsertarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInsertarKeyPressed
        // TODO add your handling code here:
        insertarkey(evt);
    }//GEN-LAST:event_txtInsertarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bntGrupo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblInsertar;
    private javax.swing.JRadioButton radioBtn;
    private javax.swing.JRadioButton radioBtn2;
    private javax.swing.JTextField txtInsertar;
    // End of variables declaration//GEN-END:variables
}
